resources:
  pipelines:
    parse_pipeline:
      name: "[${bundle.target}] Parse PDF Documents"

      # Output catalog and schema for the streaming table
      catalog: ${var.catalog}
      target: ${var.schema}

      serverless: true

      libraries:
        - glob:
            include: ../src/pipelines/parse_pdfs/transformations/**
      root_path: ../src/pipelines/parse_pdfs

      # pdf_folder_path is referenced in the SQL as ${pipeline.pdf_folder_path}
      configuration:
        pdf_folder_path: ${var.pdf_folder_path}

      continuous: false
      channel: PREVIEW # Need PREVIEW channel to be able to use ai_parse_document function
